# Generated by Django 3.0.2 on 2020-01-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200116_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FontPhoto',
        ),
    ]
