# Generated by Django 3.0.2 on 2020-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_remove_gallery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plase',
            name='photo_main',
            field=models.ImageField(default='default.jpg', upload_to='photo_main_pics'),
        ),
    ]
