# Generated by Django 3.0.2 on 2020-01-31 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20200131_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plase',
            old_name='photo_main',
            new_name='image',
        ),
    ]
