# Generated by Django 3.0.2 on 2020-01-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20200131_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='img/gallery_pics'),
        ),
        migrations.AlterField(
            model_name='plase',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='img/photo_main_pics'),
        ),
    ]
