# Generated by Django 3.0.2 on 2020-02-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20200202_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon',
            name='photo_main',
            field=models.ImageField(default='default.jpg', upload_to='img/anons', verbose_name='Изображение'),
        ),
    ]
